#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\CommandLoader\ContainerCommandLoader;
use Yiisoft\Composer\Config\Builder;
use Yiisoft\Di\Container;

$autoload = __DIR__ . '/vendor/autoload.php';

if (!is_file($autoload)) {
    die('You need to set up the project dependencies using Composer');
}

require_once $autoload;

$paramsConsole = require Builder::path('params-console-local');

$container = new Container(require Builder::path('console-local'));

$loader = new ContainerCommandLoader(
    $container,
    $paramsConsole['consoleCommands']
);

$app = new Application();

$app->setCommandLoader($loader);

$app -> run();
